version: "3.6"
volumes:
  jenkins_home:
services:
 
  main:
    image: ridingintraffic/jenkins-did
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
 
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
